const Data = [
  {
    name: "Furious Express",
    status: "moving locomotive",
    route: "MG-ES",
    load: "iron ore",
    driver: "Amanda",
    maneuverer: "Ana",
  },
  {
    name: "Thunderbolt Runner",
    status: "locomotive under maintenance",
    route: "ES-MG",
    load: "soybean",
    driver: "André",
    maneuverer: "Antonio",
  },
  {
    name: "Ironclad Voyager",
    status: "moving locomotive",
    route: "ES-MG",
    load: "soybean",
    driver: "Caio",
    maneuverer: "Carla",
  },
  {
    name: "Lightning Express",
    status: "stopped locomotive",
    route: "MG-ES",
    load: "iron ore",
    driver: "Daniela",
    maneuverer: "Douglas",
  },
  {
    name: "Mighty Hauler",
    status: "moving locomotive",
    route: "ES-MG",
    load: "soybean",
    driver: "Juliana",
    maneuverer: "Julio",
  },
  {
    name: "Silver Arrow",
    status: "stopped locomotive",
    route: "MG-ES",
    load: "iron ore",
    driver: "Luiz",
    maneuverer: "Laura",
  },
];
